#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ferris_hlc(
        KC_Q,         KC_W,         KC_E,         KC_R,         KC_T,         KC_Y,         KC_U,         KC_I,         KC_O,         KC_P,
        LSFT_T(KC_A), LT(5,KC_S),   LT(1,KC_D),   LT(3,KC_F),   KC_G,         KC_H,         LT(4,KC_J),   LT(2,KC_K),   LT(6,KC_L),   LSFT_T(KC_SCLN),
        KC_Z,         LCTL_T(KC_X), LALT_T(KC_C), KC_V,         KC_B,         KC_N,         KC_M,         LALT_T(KC_COMM), LCTL_T(KC_DOT), KC_SLSH,
                                                  KC_P0,        KC_BSPC,      LT(7,KC_SPC), KC_P1,
        KC_MUTE,      KC_NO,        KC_NO,        KC_NO,        KC_NO,        KC_MUTE,      KC_NO,        KC_NO,        KC_NO,        KC_NO
    ),
    [1] = LAYOUT_ferris_hlc(
        RM_TOGG,      RM_NEXT,      RM_HUEU,      RM_SATU,      RM_VALU,      RM_SPDU,      MS_BTN1,      MS_WHLU,      MS_BTN2,      KC_TRNS,
        KC_TRNS,      MS_BTN2,      KC_NO,        MS_BTN1,      KC_TRNS,      KC_TRNS,      MS_LEFT,      MS_DOWN,      MS_UP,        MS_RGHT,
        KC_TRNS,      RM_PREV,      RM_HUED,      RM_SATD,      RM_VALD,      RM_SPDD,      MS_WHLL,      MS_WHLD,      MS_WHLR,      KC_TRNS,
                                                  KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
        _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______
    ),
    [2] = LAYOUT_ferris_hlc(
        KC_TRNS,      KC_TRNS,      KC_PGUP,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
        KC_LEFT,      KC_UP,        KC_DOWN,      KC_RGHT,      KC_TRNS,      KC_TRNS,      KC_LGUI,      KC_NO,        LCTL(KC_LALT), LCA(KC_LSFT),
        KC_TRNS,      KC_HOME,      KC_PGDN,      KC_END,       KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
                                                  KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
        _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______
    ),
    [3] = LAYOUT_ferris_hlc(
        KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_UNDS,      KC_PIPE,      KC_QUOT,      KC_TRNS,
        KC_CIRC,      KC_ASTR,      KC_AMPR,      KC_NO,        KC_TRNS,      KC_HASH,      KC_TILD,      KC_SLSH,      KC_DQUO,      KC_DLR,
        KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_MINS,      KC_BSLS,      KC_GRV,       KC_TRNS,
                                                  RM_PREV,      KC_TRNS,      KC_TRNS,      RM_NEXT,
        _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______
    ),
    [4] = LAYOUT_ferris_hlc(
        KC_TRNS,      KC_COLN,      KC_LT,        KC_GT,        KC_SCLN,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
        KC_LCBR,      KC_RCBR,      KC_LPRN,      KC_RPRN,      KC_AT,        KC_TRNS,      KC_NO,        KC_EQL,       KC_PLUS,      KC_PERC,
        KC_TRNS,      KC_EXLM,      KC_LBRC,      KC_RBRC,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
                                                  KC_VOLD,      KC_TRNS,      KC_TRNS,      KC_VOLU,
        _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______

    ),
    [5] = LAYOUT_ferris_hlc(
        KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_F7,        KC_F8,        KC_F9,        KC_F10,
        KC_TRNS,      KC_NO,        LCTL(KC_LALT), KC_TRNS,     KC_TRNS,      KC_TRNS,      KC_F4,        KC_F5,        KC_F6,        KC_F11,
        KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_F1,        KC_F2,        KC_F3,        KC_F12,
                                                  KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
        _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______

    ),
    [6] = LAYOUT_ferris_hlc(
        KC_PSLS,      KC_7,         KC_8,         KC_9,         KC_PPLS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
        KC_0,         KC_1,         KC_2,         KC_3,         KC_PMNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_NO,        KC_TRNS,
        KC_PAST,      KC_4,         KC_5,         KC_6,         KC_PEQL,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
                                                  KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
        _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______

    ),
    [7] = LAYOUT_ferris_hlc(
        KC_TRNS,      KC_TRNS,      KC_COLN,      KC_ESC,       KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_DEL,
        KC_TRNS,      KC_PERC,      KC_SLSH,      KC_ENT,       KC_TRNS,      DF(1),        KC_LGUI,      KC_TRNS,      KC_TRNS,      KC_TRNS,
        KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_EXLM,      KC_TRNS,      DF(0),        KC_TRNS,      RALT_T(KC_COMM), RCTL_T(KC_DOT), QK_BOOT,
                                                  KC_TRNS,      KC_TAB,       KC_NO,        KC_TRNS,
        _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______,      _______

    )
};
#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [1] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [2] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [3] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [4] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [5] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [6] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [7] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)}
};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


